### ISSUE TITLE
Set up coverage for master branch too

### ISSUE THREAD

**Issue by damithc** [CS2103AUG2016-W09-C2/main#105]
Guys, can set up coverage reporting for your master branch too?

![image](https://cloud.githubusercontent.com/assets/1673303/19616677/38d6769e-984c-11e6-8271-d0ebc989cb6a.png)

**Comment by brandonyeoxg** [comment]
@damithc Hello prof , I am confused. On the readme of our master branch it states the coverage. Please advise.

Edited:
I think I know what was the problem, will add it in asap.

**Comment by damithc** [comment]
I think you set it up for the 'develop' branch, not the 'master' branch.

**Comment by brandonyeoxg** [comment]
Yes I noticed that. Thank you prof for the assistance.
Will close this issue once it is solved.
Can I also close the issue on v0.3 feedback?
