### ISSUE TITLE
Problems regarding date format

### ISSUE THREAD

**Issue by Yichen-D** [CS2103AUG2016-W09-C2/main#40]
Current problems:
For time part:
Our nattyParser(or Parser) can recognize: 2.00am, 11am
but not 02.00am, 11.30am

**Comment by brandonyeoxg** [comment]
Yes I noticed that too yesterday, could it be that our natty parser version is the problem?
Since the it works on the natty website and it is V1.2 while our's is v0.8

**Comment by brandonyeoxg** [comment]
We can use gradle to build dependencies for natty to v0.12 but lets not put it in milestone v0.2
