### ISSUE TITLE
V0.3 feedback

### ISSUE THREAD

**Issue by damithc** [CS2103AUG2016-W09-C2/main#79]
I'm giving you guys one day to do any further updates to the user guide and developer guide (_**if**_ you want to do any further updates based on what I said during the tutorial)  before I review them on GitHub.

Remember to do the V0.4 plan (looks very sparse at the moment) before you start working on V0.4

**Comment by brandonyeoxg** [comment]
Yes Prof noted with thanks.

**Comment by damithc** [comment]
My feedback below:

# Developer Guide
- The diagramming tool you use cannot show object creation properly? Compare your diagram with the one in our original developer guide.
  ![image](https://cloud.githubusercontent.com/assets/1673303/19547546/4e581c48-96cb-11e6-8ef6-61d73c97fbaa.png)
- Suggested additions:
  - Explain how your design support undo/redo. There are multiple ways this can be done, so it will be useful to explain how you do it and why you chose to do it that way.
- It may be more practical to give a few examples of interesting test cases and explain the thinking behind how you arrived at those test cases, rather than try to give a comprehensive list of all test cases.

# User Guide
- Good job adding a lot of screen shots. In future, you might want to use partial screenshots capturing only the part in concern. Otherwise you'll have to update all screenshots when some minor detail of the GUI changes.
- Why is this info relevant to the user? 
  ![image](https://cloud.githubusercontent.com/assets/1673303/19547661/2d8b704a-96cc-11e6-8c89-bf7b418f2b60.png)
- Does the user guide explain why different tasks are in different colors?
- Why 3 undos only? Seems like an arbitrary restriction.
- Try not to repeat same thing too many times e.g. 
  ![image](https://cloud.githubusercontent.com/assets/1673303/19547708/7ed5fe8e-96cc-11e6-8f71-37eaae19563e.png)
- The 'Command summary' section will be used heavily by our testers. Try to make it easy to use as possible. e.g. give examples for each command.

**Comment by damithc** [comment]
Also, see the discussion in [this issue](https://github.com/CS2103AUG2016-W09-C3/main/issues/86#issuecomment-255051389)
